# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55a0868081f01d05fa15bdd92a6efaed7937ab929d9ee88a5c8d3d69f0f574a3873bb044e1cb69bfede57350eac818b70d557e9446abac1e566fdafe2dd6cf2a

test:
  secret_key_base: 7e104221fbf2f34f1e453321b278b01459c72c30dfaaa55000ecb9d000461047d7de30ce9c6bc2b46f706b82705b94cfd0e103f6539fcbd5298e9babc11258f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
